SmNav2Test7:
    ros__parameters:
        use_sim_time: true
        signal_detector_loop_freq: 20.0
        clear_angular_distance_threshold: 0.1 # 0.05
        clear_point_distance_threshold:  0.4 #0.1
        record_angular_distance_threshold: 0.005
        record_point_distance_threshold: 0.1
        max_visited_points: 15 #50 

        waypoints_file: $(pkg_share)/config/navigation_waypoints_1.yaml
