waypoints:
#  # POINT R0  
  - position:
      x: 0.0
      y: 0.0 
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
# POINT R1
  - position:
      x: -15.5
      y: -23.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.6774078692237631
      w: 0.7356076255135758
# POINT R2
  - position:
      x: 9.0
      y: -23.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.7162844020749494
      w: 0.6978084660880322
# POINT R3
  - position:
      x: 8.5
      y: 24.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R4
  - position:
      x: -1.0
      y: 11.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.6774078692237631
      w: 0.7356076255135758
# POINT R5
  - position:
      x: -6.5
      y: 14.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R6
  - position:
      x: -16.5
      y: 22.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R7
  - position:
      x: -16.5
      y: 6.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R8
  - position:
      x: -6.5
      y: 22.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R9
  - position:
      x: 8.5
      y: 24.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# POINT R10
  - position:
      x: 8.5
      y: 1.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999992656071339
      w: 0.0012119344836913665
# # POINT R11
#   - position:
#       x: -2.5
#       y: 2.25
#       z: 0.0
#     orientation:
#       x: 0.0
#       y: 0.0
#       z: -0.6774078692237631
#       w: 0.7356076255135758
# # POINT R13
#   - position:
#       x: -2.5
#       y: 0.5
#       z: 0.0
#     orientation:
#       x: 0.0
#       y: 0.0
#       z: -0.6774078692237631
#       w: 0.7356076255135758

  # # POINT R1
  # - position:
  #     x: 18.10907715
  #     y: 52.59328613
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R2
  # - position:
  #     x: 2.850
  #     y: 52.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R3
  # - position:
  #     x: 2.85
  #     y: 42.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R4
  # - position:
  #     x: 7.85
  #     y: 36.2
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R5
  # - position:
  #     x: 7.85
  #     y: 24.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # POINT R7
  # - position:
  #     x: 1.40
  #     y: 26.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # POINT R8
  # - position:
  #     x: -3.70
  #     y: 26.70
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R10
  # - position:
  #     x: -8.0
  #     y: 43.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R11
  # - position:
  #     x: -29.7
  #     y: 43.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R12
  # - position:
  #     x: -29.7
  #     y: 65.20
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R13
  # - position:
  #     x: -35.15
  #     y: 65.2
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R14
  # - position:
  #     x: -35.15
  #     y: 70.50
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R15
  # - position:
  #     x: -22.70
  #     y: 70.50
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R16
  # - position:
  #     x: -20.80
  #     y: 63.90
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R17
  # - position:
  #     x: 1.95
  #     y: 63.90
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R18
  # - position:
  #     x: 1.95.80
  #     y: 71.15
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R19
  # - position:
  #     x: -4.25
  #     y: 71.15
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R20
  # - position:
  #     x: -4.25
  #     y: 62.00
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R21
  # - position:
  #     x: -13.80
  #     y: 62.00
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
  # # POINT R22
  # - position:
  #     x: -15.50
  #     y: 51.0
  #     z: 0.0
  #   orientation:
  #     x: 0.0
  #     y: -0.0
  #     z: 0.0
  #     w: 1.0
